# Generated by Django 6.0.6 on 2026-08-14 21:48

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DueDiligence',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_verified', models.BooleanField(default=False)),
                ('conflict_free', models.BooleanField(default=False)),
                ('oecd_conformant', models.BooleanField(default=False)),
                ('oecd_step', models.PositiveSmallIntegerField(default=1)),
                ('statement', models.CharField(blank=True, max_length=255)),
                ('attested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestations', to=settings.AUTH_USER_MODEL)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='due_diligence', to='production.goldbatch')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KycScreening',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_name', models.CharField(max_length=160)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('purpose', models.CharField(default='Buyer onboarding', max_length=120)),
                ('sanctions_hit', models.BooleanField(default=False)),
                ('pep', models.BooleanField(default=False)),
                ('risk_rating', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('flagged', 'Flagged for review'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings_performed', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_screenings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
