# Generated by Django 6.0.6 on 2026-08-14 21:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrator'), ('ceo', 'GoldBod CEO'), ('goldbod_officer', 'GoldBod Officer'), ('miner', 'Licensed Miner'), ('buying_agent', 'Buying Agent'), ('tier1_buyer', 'Tier 1 Buyer'), ('tier2_buyer', 'Tier 2 Buyer'), ('aggregator', 'Aggregator'), ('assayer', 'Assayer'), ('refinery_operator', 'Refinery Operator'), ('exporter', 'Exporter'), ('customs_officer', 'Customs Officer'), ('security_agency', 'Security Agency'), ('bog_officer', 'Bank of Ghana Officer'), ('ministry_official', 'Ministry Official'), ('env_officer', 'Environmental Protection Officer'), ('international_buyer', 'International Buyer'), ('mining_company', 'Mining Company'), ('rider', 'Delivery Rider'), ('driver', 'Delivery Driver')], db_index=True, default='miner', max_length=32)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('ghana_card_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('is_verified', models.BooleanField(default=False)),
                ('mfa_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
