# Generated by Django 6.0.6 on 2026-09-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_district_user_latitude_user_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('ceo', 'GoldBod CEO'), ('goldbod_officer', 'GoldBod Officer'), ('miner', 'Licensed Miner'), ('buying_agent', 'Buying Agent'), ('tier1_buyer', 'Tier 1 Buyer'), ('tier2_buyer', 'Tier 2 Buyer'), ('aggregator', 'Aggregator'), ('assayer', 'Assayer'), ('refinery_operator', 'Refinery Operator'), ('exporter', 'Exporter'), ('customs_officer', 'Customs Officer'), ('security_agency', 'Security Agency'), ('bog_officer', 'Bank of Ghana Officer'), ('ministry_official', 'Ministry Official'), ('env_officer', 'Environmental Protection Officer'), ('international_buyer', 'International Buyer'), ('mining_company', 'Mining Company'), ('rider', 'Delivery Rider'), ('driver', 'Delivery Driver'), ('independent_auditor', 'Independent Auditor')], db_index=True, default='miner', max_length=32),
        ),
    ]
