# Generated by Django 6.0.6 on 2026-09-08 12:52

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('base_role', models.CharField(choices=[('super_admin', 'Super Administrator'), ('ceo', 'GoldBod CEO'), ('goldbod_officer', 'GoldBod Officer'), ('miner', 'Licensed Miner'), ('buying_agent', 'Buying Agent'), ('tier1_buyer', 'Tier 1 Buyer'), ('tier2_buyer', 'Tier 2 Buyer'), ('aggregator', 'Aggregator'), ('assayer', 'Assayer'), ('refinery_operator', 'Refinery Operator'), ('exporter', 'Exporter'), ('customs_officer', 'Customs Officer'), ('security_agency', 'Security Agency'), ('bog_officer', 'Bank of Ghana Officer'), ('ministry_official', 'Ministry Official'), ('env_officer', 'Environmental Protection Officer'), ('international_buyer', 'International Buyer'), ('mining_company', 'Mining Company'), ('rider', 'Delivery Rider'), ('driver', 'Delivery Driver'), ('independent_auditor', 'Independent Auditor')], max_length=32)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.position'),
        ),
    ]
