# Generated by Django 6.0.6 on 2026-09-08 09:30

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0001_initial'),
        ('miners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedMiningSite',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('region', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(default='satellite', max_length=40)),
                ('confidence', models.FloatField(default=0.0)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operator_name', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('suspected_illegal', 'Suspected illegal'), ('confirmed_illegal', 'Confirmed illegal'), ('licensed', 'Within licensed concession'), ('dismissed', 'Dismissed')], db_index=True, default='unverified', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('matched_concession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='miners.concession')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
