# Generated by Django 6.0.6 on 2026-08-14 21:48

import django.db.models.deletion
import django_mongodb_backend.fields
import exports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportCertificate',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(default=exports.models.make_certificate_number, editable=False, max_length=24, unique=True)),
                ('destination_country', models.CharField(max_length=80)),
                ('fine_weight_g', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fineness', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('revoked', 'Revoked')], db_index=True, default='draft', max_length=10)),
                ('certificate_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('anchored_tx', models.CharField(blank=True, max_length=128)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='export_qr/%Y/%m/')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_certificates', to='production.goldbatch')),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_certificates', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
