# Generated by Django 6.0.6 on 2026-09-08 10:17

import django.db.models.deletion
import django_mongodb_backend.fields
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gis', '0002_detectedminingsite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLink',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=reports.models.make_token, editable=False, max_length=40, unique=True)),
                ('title', models.CharField(default='Report illegal mining', max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('submissions', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicReport',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('illegal_mining', 'Illegal mining'), ('environmental', 'Environmental damage'), ('smuggling', 'Smuggling / suspicious movement'), ('safety', 'Safety / community harm'), ('other', 'Other')], db_index=True, default='illegal_mining', max_length=20)),
                ('description', models.TextField()),
                ('reporter_name', models.CharField(blank=True, max_length=120)),
                ('reporter_phone', models.CharField(blank=True, max_length=40)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('location_text', models.CharField(blank=True, max_length=200)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=14)),
                ('officer_note', models.TextField(blank=True, default='')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='gis.detectedminingsite')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.reportlink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
