web: gunicorn goldtrace.wsgi:application --bind 0.0.0.0:$PORT --workers 4
worker: celery -A goldtrace worker -l info
# On Railway, run migrations via the service's Pre-Deploy Command (Settings ->
# Deploy -> Pre-Deploy Command):  python manage.py migrate
