# Generated by Django 6.0.6 on 2026-08-14 21:48

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_type', models.CharField(choices=[('tier1_buyer', 'Tier 1 Buyer'), ('tier2_buyer', 'Tier 2 Buyer'), ('aggregator', 'Aggregator'), ('self_financing_aggregator', 'Self-financing Aggregator'), ('refiner', 'Refiner'), ('jeweller', 'Jeweller / Fabricator'), ('smelter', 'Smelter'), ('transporter', 'Transporter (bullion)'), ('storage', 'Storage / Vault'), ('importer', 'Importer'), ('exporter', 'Exporter')], db_index=True, max_length=32)),
                ('license_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='active', max_length=10)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('operating_areas', models.CharField(blank=True, max_length=200)),
                ('working_capital_ghs', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('trade_capital_ghs', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
