# Generated by Django 6.0.6 on 2026-08-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='renewal_document',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='license',
            name='renewal_requested',
            field=models.BooleanField(default=False),
        ),
    ]
