# Generated by Django 6.0.6 on 2026-08-14 21:48

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_type', models.CharField(choices=[('missing', 'Reported missing'), ('stolen', 'Reported stolen'), ('tamper', 'Tamper / seal broken'), ('unaccounted', 'Unaccounted (custody gap)')], db_index=True, max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('recovered', 'Recovered'), ('closed', 'Closed')], db_index=True, default='open', max_length=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('last_seen_lat', models.FloatField(blank=True, null=True)),
                ('last_seen_lng', models.FloatField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='production.goldbatch')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
