# Generated by Django 6.0.6 on 2026-08-14 21:48

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier_type', models.CharField(choices=[('rider', 'Rider (motorbike)'), ('driver', 'Driver (vehicle)')], db_index=True, max_length=8)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('available', 'Available'), ('on_delivery', 'On delivery')], db_index=True, default='offline', max_length=12)),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('max_weight_kg', models.FloatField(default=20.0)),
                ('is_bonded', models.BooleanField(default=True)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('registration_no', models.CharField(blank=True, max_length=40)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('rating', models.FloatField(default=5.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier_type', models.CharField(choices=[('rider', 'Rider (motorbike)'), ('driver', 'Driver (vehicle)')], max_length=8)),
                ('parcel_weight_kg', models.FloatField(default=1.0)),
                ('parcel_note', models.CharField(blank=True, max_length=160)),
                ('seal_number', models.CharField(blank=True, max_length=40)),
                ('escort_required', models.BooleanField(default=False)),
                ('escort_ref', models.CharField(blank=True, max_length=60)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('pickup_address', models.CharField(blank=True, max_length=200)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('dropoff_address', models.CharField(blank=True, max_length=200)),
                ('distance_km', models.FloatField(default=0.0)),
                ('price_ghs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('eta_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('searching', 'Searching for courier'), ('offered', 'Offered to courier'), ('accepted', 'Courier accepted'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='searching', max_length=12)),
                ('courier_lat', models.FloatField(blank=True, null=True)),
                ('courier_lng', models.FloatField(blank=True, null=True)),
                ('courier_updated_at', models.DateTimeField(blank=True, null=True)),
                ('handed_over', models.BooleanField(default=False)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('received_by_buyer', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='production.goldbatch')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='logistics.courier')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_requests', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
