import { Button, Card, Stack, Table, TableBody, TableCell, TableHead, TableRow,
  Typography } from "@mui/material";
import PrintIcon from "@mui/icons-material/Print";
import { useReceiptsQuery } from "../services/api";
import type { Receipt } from "../types";

function printReceipt(r: Receipt) {
  const w = window.open("", "_blank", "width=560,height=720");
  if (!w) return;
  const date = new Date().toLocaleString("en-GB");
  w.document.write(`
    <html><head><title>Receipt ${r.reference}</title>
    <style>
      *{font-family:Georgia,serif;color:#0C1813}
      body{padding:36px;max-width:520px;margin:auto}
      .bar{height:6px;background:linear-gradient(90deg,#0C1813,#C9A227)}
      h1{font-size:22px;margin:18px 0 2px}
      .sub{color:#6b7770;font-size:12px;letter-spacing:2px;text-transform:uppercase}
      table{width:100%;border-collapse:collapse;margin-top:22px}
      td{padding:9px 0;border-bottom:1px solid #e7e2d5;font-size:14px}
      td.k{color:#6b7770}
      .amt{font-size:26px;font-weight:bold;margin-top:8px}
      .ft{margin-top:28px;font-size:11px;color:#98a29a}
    </style></head><body>
    <div class="bar"></div>
    <h1>GOLDTRACE · GoldBod</h1>
    <div class="sub">Official Payment Receipt</div>
    <table>
      <tr><td class="k">Reference</td><td style="text-align:right">${r.reference}</td></tr>
      <tr><td class="k">Gold batch</td><td style="text-align:right">${r.batch_code}</td></tr>
      <tr><td class="k">Paid by (buyer)</td><td style="text-align:right">${r.payer_name}</td></tr>
      <tr><td class="k">Paid to (seller)</td><td style="text-align:right">${r.payee_name}</td></tr>
      <tr><td class="k">Date</td><td style="text-align:right">${date}</td></tr>
    </table>
    <div class="amt">${r.amount} ${r.currency}</div>
    <div class="ft">Generated by GOLDTRACE Ghana · Ghana Gold Board · This is a system-issued record of a gold purchase transaction.</div>
    <script>window.onload=()=>window.print()</script>
    </body></html>`);
  w.document.close();
}

export default function Receipts() {
  const { data } = useReceiptsQuery();
  const rows = data?.results ?? [];
  return (
    <Stack spacing={3}>
      <div>
        <Typography variant="h4">Payment receipts</Typography>
        <Typography color="text.secondary">
          Proof of who paid for each batch — issued when a gold purchase completes. Print one for your customer.
        </Typography>
      </div>
      <Card>
        <Table>
          <TableHead><TableRow>
            <TableCell>Reference</TableCell><TableCell>Batch</TableCell>
            <TableCell>Paid by</TableCell><TableCell>Paid to</TableCell>
            <TableCell>Amount</TableCell><TableCell align="right">Receipt</TableCell>
          </TableRow></TableHead>
          <TableBody>
            {rows.map((r) => (
              <TableRow key={r.id} hover>
                <TableCell className="mono">{r.reference}</TableCell>
                <TableCell className="mono">{r.batch_code}</TableCell>
                <TableCell>{r.payer_name}</TableCell>
                <TableCell>{r.payee_name}</TableCell>
                <TableCell>{r.amount} {r.currency}</TableCell>
                <TableCell align="right">
                  <Button size="small" startIcon={<PrintIcon />} onClick={() => printReceipt(r)}>
                    Print
                  </Button>
                </TableCell>
              </TableRow>
            ))}
            {rows.length === 0 && <TableRow><TableCell colSpan={6}>
              <Typography color="text.secondary">No receipts yet.</Typography></TableCell></TableRow>}
          </TableBody>
        </Table>
      </Card>
    </Stack>
  );
}
