# Generated by Django 6.0.6 on 2026-08-14 21:48

import django.db.models.deletion
import django_mongodb_backend.fields
import production.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldBatch',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_code', models.CharField(default=production.models.make_batch_code, editable=False, max_length=24, unique=True)),
                ('gross_weight_g', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fine_weight_g', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('fineness', models.PositiveIntegerField(blank=True, help_text='Purity in parts per 1000 (e.g. 995).', null=True)),
                ('status', models.CharField(choices=[('created', 'Created at source'), ('assayed', 'Assayed'), ('in_transit', 'In transit'), ('refined', 'Refined'), ('exported', 'Exported')], db_index=True, default='created', max_length=12)),
                ('security_status', models.CharField(choices=[('normal', 'Normal'), ('flagged', 'Flagged'), ('missing', 'Reported missing'), ('stolen', 'Reported stolen'), ('recovered', 'Recovered')], db_index=True, default='normal', max_length=12)),
                ('source_point', models.JSONField(blank=True, default=dict, help_text='GeoJSON Point of extraction.')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='batch_qr/%Y/%m/')),
                ('passport_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('anchored_tx', models.CharField(blank=True, max_length=128)),
                ('concession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='miners.concession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_batches', to=settings.AUTH_USER_MODEL)),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='miners.miner')),
            ],
            options={
                'verbose_name_plural': 'gold batches',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('origin', 'Origin / creation'), ('transfer', 'Ownership transfer'), ('assay', 'Assay'), ('refine', 'Refining'), ('export', 'Export'), ('customs', 'Customs clearance')], max_length=12)),
                ('from_party', models.CharField(blank=True, max_length=160)),
                ('to_party', models.CharField(blank=True, max_length=160)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('anchored_tx', models.CharField(blank=True, max_length=128)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='production.goldbatch')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('xrf', 'XRF'), ('fire_assay', 'Fire assay')], default='xrf', max_length=12)),
                ('gross_weight_g', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fine_weight_g', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fineness', models.PositiveSmallIntegerField(help_text='Parts per 1000')),
                ('certificate_no', models.CharField(default=production.models.make_assay_no, editable=False, max_length=24, unique=True)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('assayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assays', to=settings.AUTH_USER_MODEL)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assay', to='production.goldbatch')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
