# Generated by Django 6.0.6 on 2026-08-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldbatch',
            name='asking_price_ghs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='goldbatch',
            name='listed_for_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='goldbatch',
            name='seal_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
