# Generated by Django 6.0.6 on 2026-08-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_goldbatch_asking_price_ghs_goldbatch_listed_for_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldbatch',
            name='field_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='goldbatch',
            name='origin_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldbatch',
            name='origin_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
