# Generated by Django 6.0.6 on 2026-09-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_goldbatch_field_notes_goldbatch_origin_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldbatch',
            name='is_aggregated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goldbatch',
            name='mass_balance_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldbatch',
            name='refine_input_g',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='goldbatch',
            name='refine_loss_g',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='goldbatch',
            name='refine_output_g',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='goldbatch',
            name='refine_residue_g',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='goldbatch',
            name='refine_sample_g',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='goldbatch',
            name='source_lots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
