# Generated by Django 6.0.6 on 2026-09-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='entry_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='prev_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
