# Generated by Django 6.0.6 on 2026-09-08 09:30

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_entry_hash_auditlog_prev_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleFeatures',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=32, unique=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
