# Generated by Django 6.0.6 on 2026-09-08 12:52

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rolefeatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='Ghana Gold Board', max_length=120)),
                ('tagline', models.CharField(default='National Digital Trust Platform', max_length=200)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('report_form_title', models.CharField(default='Report illegal mining to GoldBod', max_length=160)),
                ('risk_block_threshold', models.PositiveSmallIntegerField(default=70)),
                ('risk_review_threshold', models.PositiveSmallIntegerField(default=45)),
                ('mass_balance_tolerance_pct', models.FloatField(default=0.5)),
                ('fx_discrepancy_pct', models.FloatField(default=5.0)),
                ('max_report_attachments', models.PositiveSmallIntegerField(default=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
